title:              The Journal
email:              vedantanilsatav@gmail.com
description:        A physical manifestation of my experiences and thoughts
author:             Vedant Satav
baseurl:            "/"
url:                "https://vedantsatav.github.io"

# Social Profiles
twitter_username:   
github_username:    vedantsatav
facebook_username:  Vedant Satav
linkedin_username:  Vedant Satav

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
